title: Ji's Blog
author: Ji


markdown: kramdown

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"
use_math: true

profile-picture: assets/self-p.png
favicon_location: assets/favicon.ico

# 代码块的设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

highlighter: rouge

Timezone : 'Asia/Beijing'

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About me"
   link: "about"
 #- name: "Resume"
 #  absolute-link: "https://rahul-bothra.github.io/CV.pdf"
